# CNN 기본연산

> ### Load Module

In [1]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

print("NumPy Version :{}".format(np.__version__))
print("TensorFlow Version :{}".format(tf.__version__))
print("Matplotlib Version :{}".format(plt.matplotlib.__version__))

NumPy Version :1.18.5
TensorFlow Version :2.3.0
Matplotlib Version :3.2.2


In [2]:
def Print_Array(np_array:np.ndarray, title:str)->None:
  print("Shape of {} : {}".format(title,np_array.shape))
  print(np_array)

## [예제1] 2D Convolution

> ### [ Shape 정보 ]
> ### Input, Output Shape => NHWC format
> ### Filter Shape => [filter_height, filter_width, in_channels, out_channels]

> ### [Conv Exam1] Input shape = (1,5,5,1), Filter = (2,2,1,1)

In [3]:
print("[Conv Exam1] Input shape(NHWC) = (1,5,5,1), Filter = (2,2,1,1)")

np_input = np.arange(1,26,1,dtype=np.float32).reshape((1,5,5,1))
np_filter = np.array([1,1,1,1],dtype=np.float32).reshape((2,2,1,1))

input_constant = tf.constant(np_input)
filter_constant = tf.constant(np_filter)

conv = tf.nn.conv2d(input_constant, filters=filter_constant, strides=1, padding="VALID")
out = conv.numpy()

Print_Array(np_input, "Input")
Print_Array(np_filter, "Filter")
Print_Array(out, "Output")

[Conv Exam1] Input shape(NHWC) = (1,5,5,1), Filter = (2,2,1,1)
Shape of Input : (1, 5, 5, 1)
[[[[ 1.]
   [ 2.]
   [ 3.]
   [ 4.]
   [ 5.]]

  [[ 6.]
   [ 7.]
   [ 8.]
   [ 9.]
   [10.]]

  [[11.]
   [12.]
   [13.]
   [14.]
   [15.]]

  [[16.]
   [17.]
   [18.]
   [19.]
   [20.]]

  [[21.]
   [22.]
   [23.]
   [24.]
   [25.]]]]
Shape of Filter : (2, 2, 1, 1)
[[[[1.]]

  [[1.]]]


 [[[1.]]

  [[1.]]]]
Shape of Output : (1, 4, 4, 1)
[[[[16.]
   [20.]
   [24.]
   [28.]]

  [[36.]
   [40.]
   [44.]
   [48.]]

  [[56.]
   [60.]
   [64.]
   [68.]]

  [[76.]
   [80.]
   [84.]
   [88.]]]]


> ### [Conv Exam2] Input shape = (1,5,5,3), Filter = (2,2,3,1)

In [4]:
print("[Conv Exam2] Input shape = (1,5,5,3), Filter = (2,2,3,1)")

np_input = np.arange(1,76,1,dtype=np.float32).reshape((1,5,5,3))
np_filter = np.array([1]*12,dtype=np.float32).reshape((2,2,3,1))

input_constant = tf.constant(np_input)
filter_constant = tf.constant(np_filter)

conv = tf.nn.conv2d(input_constant, filters=filter_constant, strides=1, padding="VALID")
out = conv.numpy()

Print_Array(np_input, "Input")
Print_Array(np_filter, "Filter")
Print_Array(out, "Output")

[Conv Exam2] Input shape = (1,5,5,3), Filter = (2,2,3,1)
Shape of Input : (1, 5, 5, 3)
[[[[ 1.  2.  3.]
   [ 4.  5.  6.]
   [ 7.  8.  9.]
   [10. 11. 12.]
   [13. 14. 15.]]

  [[16. 17. 18.]
   [19. 20. 21.]
   [22. 23. 24.]
   [25. 26. 27.]
   [28. 29. 30.]]

  [[31. 32. 33.]
   [34. 35. 36.]
   [37. 38. 39.]
   [40. 41. 42.]
   [43. 44. 45.]]

  [[46. 47. 48.]
   [49. 50. 51.]
   [52. 53. 54.]
   [55. 56. 57.]
   [58. 59. 60.]]

  [[61. 62. 63.]
   [64. 65. 66.]
   [67. 68. 69.]
   [70. 71. 72.]
   [73. 74. 75.]]]]
Shape of Filter : (2, 2, 3, 1)
[[[[1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]]]]
Shape of Output : (1, 4, 4, 1)
[[[[132.]
   [168.]
   [204.]
   [240.]]

  [[312.]
   [348.]
   [384.]
   [420.]]

  [[492.]
   [528.]
   [564.]
   [600.]]

  [[672.]
   [708.]
   [744.]
   [780.]]]]


> ### [Conv Exam3] Input shape = (1,5,5,3), Filter = (2,2,3,6)

In [5]:
print("[Conv Exam3] Input shape = (1,5,5,3), Filter = (2,2,3,6)")

np_input = np.arange(1,76,1,dtype=np.float32).reshape((1,5,5,3))
np_filter = np.array([1]*2*2*3*6,dtype=np.float32).reshape((2,2,3,6))

input_constant = tf.constant(np_input)
filter_constant = tf.constant(np_filter)

conv = tf.nn.conv2d(input_constant, filters=filter_constant, strides=1, padding="VALID")
out = conv.numpy()

Print_Array(np_input, "Input")
Print_Array(np_filter, "Filter")
Print_Array(out, "Output")

[Conv Exam3] Input shape = (1,5,5,3), Filter = (2,2,3,6)
Shape of Input : (1, 5, 5, 3)
[[[[ 1.  2.  3.]
   [ 4.  5.  6.]
   [ 7.  8.  9.]
   [10. 11. 12.]
   [13. 14. 15.]]

  [[16. 17. 18.]
   [19. 20. 21.]
   [22. 23. 24.]
   [25. 26. 27.]
   [28. 29. 30.]]

  [[31. 32. 33.]
   [34. 35. 36.]
   [37. 38. 39.]
   [40. 41. 42.]
   [43. 44. 45.]]

  [[46. 47. 48.]
   [49. 50. 51.]
   [52. 53. 54.]
   [55. 56. 57.]
   [58. 59. 60.]]

  [[61. 62. 63.]
   [64. 65. 66.]
   [67. 68. 69.]
   [70. 71. 72.]
   [73. 74. 75.]]]]
Shape of Filter : (2, 2, 3, 6)
[[[[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]]]
Shape of Output : (1, 4, 4, 6)
[[[[132. 132. 132. 132. 132. 132.]
   [168. 168. 168. 168. 168. 168.]
   [204. 204. 204. 204. 204. 204.]
   [240. 240. 240. 240.

## [예제2] 2D Convolution : Padding

>### [Conv-Padding Exam] Input shape(NHWC) = (1,5,5,1), Filter = (3,3,1,1)

In [6]:
print("[Conv-Padding Exam] Input shape(NHWC) = (1,5,5,1), Filter = (3,3,1,1)")

np_input = np.arange(1,26,1,dtype=np.float32).reshape((1,5,5,1))
np_filter = np.array([1]*9,dtype=np.float32).reshape((3,3,1,1))

input_constant = tf.constant(np_input)
filter_constant = tf.constant(np_filter)

conv = tf.nn.conv2d(input_constant, filters=filter_constant, strides=1, padding="VALID")
conv_padding = tf.nn.conv2d(input_constant, filters=filter_constant, strides=1, padding="SAME")

out,out_padding = conv.numpy(), conv_padding.numpy()

Print_Array(np_input, "Input")
Print_Array(np_filter, "Filter")
Print_Array(out, "Output")
Print_Array(out_padding, "Output with Zero Padding")

[Conv-Padding Exam] Input shape(NHWC) = (1,5,5,1), Filter = (3,3,1,1)
Shape of Input : (1, 5, 5, 1)
[[[[ 1.]
   [ 2.]
   [ 3.]
   [ 4.]
   [ 5.]]

  [[ 6.]
   [ 7.]
   [ 8.]
   [ 9.]
   [10.]]

  [[11.]
   [12.]
   [13.]
   [14.]
   [15.]]

  [[16.]
   [17.]
   [18.]
   [19.]
   [20.]]

  [[21.]
   [22.]
   [23.]
   [24.]
   [25.]]]]
Shape of Filter : (3, 3, 1, 1)
[[[[1.]]

  [[1.]]

  [[1.]]]


 [[[1.]]

  [[1.]]

  [[1.]]]


 [[[1.]]

  [[1.]]

  [[1.]]]]
Shape of Output : (1, 3, 3, 1)
[[[[ 63.]
   [ 72.]
   [ 81.]]

  [[108.]
   [117.]
   [126.]]

  [[153.]
   [162.]
   [171.]]]]
Shape of Output with Zero Padding : (1, 5, 5, 1)
[[[[ 16.]
   [ 27.]
   [ 33.]
   [ 39.]
   [ 28.]]

  [[ 39.]
   [ 63.]
   [ 72.]
   [ 81.]
   [ 57.]]

  [[ 69.]
   [108.]
   [117.]
   [126.]
   [ 87.]]

  [[ 99.]
   [153.]
   [162.]
   [171.]
   [117.]]

  [[ 76.]
   [117.]
   [123.]
   [129.]
   [ 88.]]]]


## [예제3] 2D Convolution : Stride

>### [Conv - Stride  Exam] Input shape(NHWC) = (1,5,5,1), Filter = (2,2,1,1), stride 1

In [7]:
print("[Conv - Stride  Exam] Input shape(NHWC) = (1,5,5,1), Filter = (2,2,1,1)")

np_input = np.arange(1,26,1,dtype=np.float32).reshape((1,5,5,1))
np_filter = np.array([1,1,1,1],dtype=np.float32).reshape((2,2,1,1))

input_constant = tf.constant(np_input)
filter_constant = tf.constant(np_filter)

conv = tf.nn.conv2d(input_constant, filters=filter_constant, strides=1,padding="VALID")
conv2 = tf.nn.conv2d(input_constant, filters=filter_constant, strides=2,padding="VALID")

Print_Array(np_input, "Input")
Print_Array(np_filter, "Filter")
Print_Array(conv, "Output with Stride = None")
Print_Array(conv2, "Output with Stride = 2")

[Conv - Stride  Exam] Input shape(NHWC) = (1,5,5,1), Filter = (2,2,1,1)
Shape of Input : (1, 5, 5, 1)
[[[[ 1.]
   [ 2.]
   [ 3.]
   [ 4.]
   [ 5.]]

  [[ 6.]
   [ 7.]
   [ 8.]
   [ 9.]
   [10.]]

  [[11.]
   [12.]
   [13.]
   [14.]
   [15.]]

  [[16.]
   [17.]
   [18.]
   [19.]
   [20.]]

  [[21.]
   [22.]
   [23.]
   [24.]
   [25.]]]]
Shape of Filter : (2, 2, 1, 1)
[[[[1.]]

  [[1.]]]


 [[[1.]]

  [[1.]]]]
Shape of Output with Stride = None : (1, 4, 4, 1)
tf.Tensor(
[[[[16.]
   [20.]
   [24.]
   [28.]]

  [[36.]
   [40.]
   [44.]
   [48.]]

  [[56.]
   [60.]
   [64.]
   [68.]]

  [[76.]
   [80.]
   [84.]
   [88.]]]], shape=(1, 4, 4, 1), dtype=float32)
Shape of Output with Stride = 2 : (1, 2, 2, 1)
tf.Tensor(
[[[[16.]
   [24.]]

  [[56.]
   [64.]]]], shape=(1, 2, 2, 1), dtype=float32)


## [예제4] Pooling : Max Pooling

> ### [Pooling Exam1] Input shape(NHWC) = (1,4,4,1), ksize = 2, strides = 2

In [8]:
print("[Pooling Exam1] Input shape(NHWC) = (1,4,4,1), ksize = 2, strides = 2")

np_input = np.array([[1,5,6,2],[3,2,3,1],[15,2,0,4],[3,2,3,5]],dtype=np.float32).reshape(1,4,4,1)

input_constant = tf.constant(np_input)

pool = tf.nn.max_pool2d(input_constant,ksize=2,strides=2,padding="VALID")
out = pool.numpy()

Print_Array(np_input, "Input")
Print_Array(out, "Output")

[Pooling Exam1] Input shape(NHWC) = (1,4,4,1), ksize = 2, strides = 2
Shape of Input : (1, 4, 4, 1)
[[[[ 1.]
   [ 5.]
   [ 6.]
   [ 2.]]

  [[ 3.]
   [ 2.]
   [ 3.]
   [ 1.]]

  [[15.]
   [ 2.]
   [ 0.]
   [ 4.]]

  [[ 3.]
   [ 2.]
   [ 3.]
   [ 5.]]]]
Shape of Output : (1, 2, 2, 1)
[[[[ 5.]
   [ 6.]]

  [[15.]
   [ 5.]]]]


> ### [Pooling Exam2] Input shape(NHWC) = (1,5,5,1), ksize,strides = 3  or ksize,strides = 2

In [9]:
print("[Pooling Exam2] Input shape(NHWC) = (1,5,5,1), ksize,strides = 3  or ksize,strides = 2")

np_input = np.arange(1,26,1,dtype=np.float32).reshape(1,5,5,1)

Print_Array(np_input, "Input")

input_constant = tf.constant(np_input)

pool_3 = tf.nn.max_pool2d(input_constant,ksize=3,strides=3,padding="VALID")
pool_2 = tf.nn.max_pool2d(input_constant,ksize=2,strides=2,padding="VALID")

out_3, out_2 = pool_3.numpy(), pool_2.numpy()
Print_Array(out_3, "Output : ksize = 3, strides = 3")
Print_Array(out_2, "Output : ksize = 2, strides = 2")

[Pooling Exam2] Input shape(NHWC) = (1,5,5,1), ksize,strides = 3  or ksize,strides = 2
Shape of Input : (1, 5, 5, 1)
[[[[ 1.]
   [ 2.]
   [ 3.]
   [ 4.]
   [ 5.]]

  [[ 6.]
   [ 7.]
   [ 8.]
   [ 9.]
   [10.]]

  [[11.]
   [12.]
   [13.]
   [14.]
   [15.]]

  [[16.]
   [17.]
   [18.]
   [19.]
   [20.]]

  [[21.]
   [22.]
   [23.]
   [24.]
   [25.]]]]
Shape of Output : ksize = 3, strides = 3 : (1, 1, 1, 1)
[[[[13.]]]]
Shape of Output : ksize = 2, strides = 2 : (1, 2, 2, 1)
[[[[ 7.]
   [ 9.]]

  [[17.]
   [19.]]]]
