# TensorFlow 프로그래밍 기초

 ## Constant, Variable

> ### Import TensorFlow

In [1]:
import numpy as np
import tensorflow as tf

print("NumPy Version : {}".format(np.__version__))
print("TensorFlow Version : {}".format(tf.__version__))

NumPy Version : 1.18.5
TensorFlow Version : 2.3.0


> ### [1] tf.constant를 이용한 상수 Tensor 생성 예제

In [2]:
c_int = tf.constant(3)
c_float1 = tf.constant(1.239)
c_float2 = tf.constant(3, dtype= tf.float32 )
c_str = tf.constant("Hello, TensorFlow", name= 'Const_String')
# c_float3 = tf.constant(1.239, dtype= tf.int32) # TypeError

list_constant = [c_int, c_float1, c_float2, c_str]

for tensor in list_constant:
  print(tensor,"value = {}".format(tensor.numpy())) 

tf.Tensor(3, shape=(), dtype=int32) value = 3
tf.Tensor(1.239, shape=(), dtype=float32) value = 1.2389999628067017
tf.Tensor(3.0, shape=(), dtype=float32) value = 3.0
tf.Tensor(b'Hello, TensorFlow', shape=(), dtype=string) value = b'Hello, TensorFlow'


> ### [2] 각 type별 표현 범위를 출력하는 코드

In [3]:
def Print_TF_Type(title, list_types):
  print("< {} >".format(title))
  [print("{:10} : {} ~ {}".format(t.name, t.min , t.max)) for t in list_types]

list_types_float = [tf.float16, tf.float32, tf.float64]
list_types_bfloat = [tf.bfloat16]
list_types_int = [tf.int8, tf.int16, tf.int32, tf.int64]
list_types_uint = [tf.uint8, tf.uint16, tf.uint32, tf.uint64]

Print_TF_Type("Min,Max of tf.float[16,32,64]",list_types_float)
Print_TF_Type("Min,Max of tf.bfloat16",list_types_bfloat)
Print_TF_Type("Min,Max of tf.int[8,16,32,64]",list_types_int)
Print_TF_Type("Min,Max of tf.uint[8,16,32,64]",list_types_uint)

< Min,Max of tf.float[16,32,64] >
float16    : -65504.0 ~ 65504.0
float32    : -3.4028234663852886e+38 ~ 3.4028234663852886e+38
float64    : -1.7976931348623157e+308 ~ 1.7976931348623157e+308
< Min,Max of tf.bfloat16 >
bfloat16   : -3.38953139e+38 ~ 3.38953139e+38
< Min,Max of tf.int[8,16,32,64] >
int8       : -128 ~ 127
int16      : -32768 ~ 32767
int32      : -2147483648 ~ 2147483647
int64      : -9223372036854775808 ~ 9223372036854775807
< Min,Max of tf.uint[8,16,32,64] >
uint8      : 0 ~ 255
uint16     : 0 ~ 65535
uint32     : 0 ~ 4294967295
uint64     : 0 ~ 18446744073709551615


> ### [3] Rank 0(scalar)의 Constant tensor를 설정한 예제

In [4]:
SC_int = tf.constant(451, dtype= tf.int16, name= 'Const1')
SC_float = tf.constant(3.14159265359, name= 'Const2')
SC_string = tf.constant("Elephant", name= 'Const3')

list_SC = [SC_int, SC_float, SC_string]

print("SC_int.shape = {}".format(SC_int.shape))

for tensor in list_SC:
  print("Rank = {},".format(tf.rank(tensor)),tensor)

SC_int.shape = ()
Rank = 0, tf.Tensor(451, shape=(), dtype=int16)
Rank = 0, tf.Tensor(3.1415927, shape=(), dtype=float32)
Rank = 0, tf.Tensor(b'Elephant', shape=(), dtype=string)


> ### [4] Rank 1(Vector)의 Constant tensor를 설정한 예제

In [5]:
VT_int1 = tf.constant([10, 3], name= 'Const1')
VT_int2 = tf.constant([1], name= 'Const2')
VT_floats = tf.constant([3.1415, 10.23], name= 'Const3')
VT_strings = tf.constant(["Elephant", "Rabbit", "Turtle"], name= 'Const4')

list_VT = [VT_int1, VT_int2, VT_floats, VT_strings]

for tensor in list_VT:
  print("Rank = {},".format(tf.rank(tensor)),tensor)

Rank = 1, tf.Tensor([10  3], shape=(2,), dtype=int32)
Rank = 1, tf.Tensor([1], shape=(1,), dtype=int32)
Rank = 1, tf.Tensor([ 3.1415 10.23  ], shape=(2,), dtype=float32)
Rank = 1, tf.Tensor([b'Elephant' b'Rabbit' b'Turtle'], shape=(3,), dtype=string)


> ### [5] Rank 2(Matrix)의 Constant tensor를 설정한 예제

In [6]:
MT_int1 = tf.constant([[10, 3], [4, 5]], name= 'Const1')
MT_int2 = tf.constant([[1]], name= 'Const2')
MT_floats = tf.constant([[3.1415, 10.23, 9.], [2.3, 11, 15.0]], name= 'Const3')

list_MT = [MT_int1, MT_int2, MT_floats]

for tensor in list_MT:
  print("Rank = {},".format(tf.rank(tensor)),tensor)

Rank = 2, tf.Tensor(
[[10  3]
 [ 4  5]], shape=(2, 2), dtype=int32)
Rank = 2, tf.Tensor([[1]], shape=(1, 1), dtype=int32)
Rank = 2, tf.Tensor(
[[ 3.1415 10.23    9.    ]
 [ 2.3    11.     15.    ]], shape=(2, 3), dtype=float32)


> ### [6] Rank 3(Cube)의 Constant tensor를 설정한 예제

In [7]:
CB_int1 = tf.constant([[[1, 2], [3, 4]],[[5, 6], [7, 8]]], name= 'Const1')
CB_int2 = tf.constant([[[100]]], name= 'Const2')
CB_floats = tf.constant([[[3.1415, 10.23, 9.], [2.3, 11, 15.0]]], name= 'Const3')

list_CB = [CB_int1, CB_int2, CB_floats]

for tensor in list_CB:
  print("Rank = {},".format(tf.rank(tensor)),tensor)

Rank = 3, tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
Rank = 3, tf.Tensor([[[100]]], shape=(1, 1, 1), dtype=int32)
Rank = 3, tf.Tensor(
[[[ 3.1415 10.23    9.    ]
  [ 2.3    11.     15.    ]]], shape=(1, 2, 3), dtype=float32)


> ### [7] Higher rank of Tensor(image)를 정의한 예제

In [8]:
batch_images = tf.constant(0 , shape =(10, 240, 320, 3))

> ### [8] 상수를 초기값으로 하는 Variable 생성 예제

In [9]:
var_1 = tf.Variable(10)
var_2 = tf.Variable(20, dtype= tf.float64)
var_3 = tf.Variable(30, name= 'VAR_Weight')

list_var = [var_1, var_2, var_3]

for tensor in list_var:
  print("tensor = {}".format(tensor))
  print("value = {}".format(tensor.numpy()))

tensor = <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>
value = 10
tensor = <tf.Variable 'Variable:0' shape=() dtype=float64, numpy=20.0>
value = 20.0
tensor = <tf.Variable 'VAR_Weight:0' shape=() dtype=int32, numpy=30>
value = 30


> ### [9] 특정 함수에 의해 만들어진 초기값을 사용하는 Variable 생성 예제

In [10]:
var_1 = tf.Variable(tf.zeros((2,3)))
var_2 = tf.Variable(tf.ones((1,5)))
var_3 = tf.Variable(tf.eye(2,2), name= 'VAR_Weight')

list_var = [var_1, var_2, var_3]

for tensor in list_var:
  print("tensor = {}".format(tensor))
  print("value = {}".format(tensor.numpy()))

tensor = <tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>
value = [[0. 0. 0.]
 [0. 0. 0.]]
tensor = <tf.Variable 'Variable:0' shape=(1, 5) dtype=float32, numpy=array([[1., 1., 1., 1., 1.]], dtype=float32)>
value = [[1. 1. 1. 1. 1.]]
tensor = <tf.Variable 'VAR_Weight:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>
value = [[1. 0.]
 [0. 1.]]


> ### [10] Random 함수에 의해 만들어진 초기값을 사용하는 Variable 생성 예제

In [11]:
var_1 = tf.Variable(tf.random.normal((1,1)))
var_2 = tf.Variable(tf.random.truncated_normal((1,5), mean = 10, stddev = 0.1))
var_3 = tf.Variable(tf.random.uniform((2,2), minval=6, maxval=10))

list_var = [var_1, var_2, var_3]

for tensor in list_var:
  print("tensor = {}".format(tensor))
  print("value = {}".format(tensor.numpy()))

tensor = <tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[0.978218]], dtype=float32)>
value = [[0.978218]]
tensor = <tf.Variable 'Variable:0' shape=(1, 5) dtype=float32, numpy=
array([[ 9.940395, 10.061802,  9.954579, 10.000984, 10.029105]],
      dtype=float32)>
value = [[ 9.940395 10.061802  9.954579 10.000984 10.029105]]
tensor = <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[6.1165233, 7.442058 ],
       [7.329945 , 9.814873 ]], dtype=float32)>
value = [[6.1165233 7.442058 ]
 [7.329945  9.814873 ]]
